# .github/workflows/publish.yml
name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - run: npm test -- --watch=false

      - run: npm run build ngx-signal-schema

      - run: npm publish --access public --provenance
        working-directory: dist/ngx-signal-schema
